# Generated by Django 4.2.20 on 2025-05-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional description for the conversation"
            ),
        ),
    ]
