# Generated by Django 4.2.20 on 2025-06-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0002_conversation_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="state",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("error", "Error"),
                    ("awaiting_approval", "Awaiting Approval"),
                ],
                default="completed",
                help_text="Lifecycle state of the message for quick filtering",
                max_length=32,
            ),
        ),
    ]
