apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: localhost:5005/opencontracts-frontend
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: frontend-config
        env:
        - name: OPEN_CONTRACTS_REACT_APP_API_ROOT_URL
          value: "http://localhost:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000