version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  django: &django
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-yourusername}/opencontractserver_django:${TAG:-latest}
    depends_on:
      - postgres
      - redis
      - vector-embedder
      - nlm-ingestor
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  postgres:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-yourusername}/opencontractserver_postgres:${TAG:-latest}
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-yourusername}/opencontractserver_frontend:${TAG:-latest}
    container_name: frontend
    depends_on:
      - django
    env_file:
      - ./.envs/.production/.frontend

  traefik:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-yourusername}/opencontractserver_traefik:${TAG:-latest}
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  redis:
    image: redis:6
    container_name: redis

  nlm-ingestor:
    image: jscrudato/nlm-ingestor-opencontracts
    container_name: nlm-ingestor

  vector-embedder:
    image: jscrudato/vector-embedder-microservice
    container_name: vector-embedder
    environment:
      PORT: 8000

  celeryworker:
    <<: *django
    command: /start-celeryworker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  celerybeat:
    <<: *django
    command: /start-celerybeat

  flower:
    <<: *django
    command: /start-flower 