version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  nlm-ingestor:
    image: jscrudato/nlm-ingestor-opencontracts
    container_name: nlm-ingestor
    environment:
      PORT: 5001

  vector-embedder:
    image: jscrudato/vector-embedder-microservice
    container_name: vector-embedder
    environment:
      PORT: 8000

  django: &django
    build:
      context: .
      args:
        - GITHUB_ACTIONS
      dockerfile: ./compose/local/django/Dockerfile
    image: opencontractserver_local_django
    container_name: django
    depends_on:
      - postgres
      - redis
      - vector-embedder
      - nlm-ingestor
      - celeryworker
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.test/.django
      - ./.envs/.test/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: opencontractserver_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
      - ./compose/production/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.envs/.test/.postgres

  redis:
    image: redis:6
    container_name: redis

  celeryworker:
    <<: *django
    image: opencontractserver_local_celeryworker
    container_name: celeryworker
    depends_on:
      - redis
      - postgres
      - nlm-ingestor
    ports: []
    command: /start-celeryworker
