# Generated by Django 3.2.9 on 2022-04-04 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
        ('annotations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_annotations', related_query_name='doc_annotation', to='documents.document'),
        ),
    ]
