# Generated by Django 3.2.9 on 2024-05-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_auto_20230202_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationlabel',
            name='read_only',
            field=models.BooleanField(default=False),
        ),
    ]
