# Generated by Django 3.2.9 on 2022-06-13 03:17

from django.db import migrations, models
import opencontractserver.annotations.models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_alter_annotation_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelset',
            name='icon',
            field=models.FileField(blank=True, upload_to=opencontractserver.annotations.models.calculate_labelset_icon_path),
        ),
    ]
