# Generated by Django 3.2.9 on 2024-05-19 20:46
from pgvector.django import VectorExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0004_annotationlabel_read_only'),
    ]

    operations = [
        VectorExtension()
    ]
