# Generated by Django 3.2.9 on 2024-07-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0006_annotation_embedding'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['page'], name='annotations_page_0a720b_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['annotation_label'], name='annotations_annotat_346f59_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['document'], name='annotations_documen_28936f_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['corpus'], name='annotations_corpus__e1789a_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['analysis'], name='annotations_analysi_b0669b_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['creator'], name='annotations_creator_fb5624_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['created'], name='annotations_created_37a071_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['modified'], name='annotations_modifie_fa1e31_idx'),
        ),
    ]
