# Generated by Django 3.2.9 on 2024-07-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0008_auto_20240722_0710'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['relationship_label'], name='annotations_relatio_074f72_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['corpus'], name='annotations_corpus__c5066c_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['document'], name='annotations_documen_0d3178_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['analyzer'], name='annotations_analyze_fd0916_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['creator'], name='annotations_creator_06b305_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['created'], name='annotations_created_7e264a_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['modified'], name='annotations_modifie_d69db8_idx'),
        ),
    ]
