# Generated by Django 3.2.9 on 2024-07-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0009_auto_20240722_0712'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='labelset',
            index=models.Index(fields=['title'], name='annotations_title_50a22d_idx'),
        ),
        migrations.AddIndex(
            model_name='labelset',
            index=models.Index(fields=['analyzer'], name='annotations_analyze_0c3d44_idx'),
        ),
        migrations.AddIndex(
            model_name='labelset',
            index=models.Index(fields=['creator'], name='annotations_creator_071edd_idx'),
        ),
        migrations.AddIndex(
            model_name='labelset',
            index=models.Index(fields=['created'], name='annotations_created_a5540c_idx'),
        ),
        migrations.AddIndex(
            model_name='labelset',
            index=models.Index(fields=['modified'], name='annotations_modifie_e9574b_idx'),
        ),
    ]
