# Generated by Django 3.2.9 on 2024-07-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0010_auto_20240722_0712'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['document', 'creator'], name='annotations_documen_334be9_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['corpus', 'creator'], name='annotations_corpus__3a456b_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['document', 'corpus'], name='annotations_documen_739628_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['document', 'corpus', 'creator'], name='annotations_documen_e9ce17_idx'),
        ),
    ]
