# Generated by Django 4.2.15 on 2024-08-27 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0007_analysis_corpus_action"),
        ("annotations", "0012_alter_annotation_user_lock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="structural",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="annotationlabel",
            name="analyzer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="annotations",
                to="analyzer.analyzer",
            ),
        ),
    ]
