# Generated by Django 4.2.15 on 2024-08-28 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0007_analysis_corpus_action"),
        ("annotations", "0013_annotation_structural_alter_annotationlabel_analyzer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationlabel",
            name="analyzer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="annotation_labels",
                to="analyzer.analyzer",
            ),
        ),
    ]
