# Generated by Django 4.2.15 on 2024-09-01 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0007_analysis_corpus_action"),
        ("annotations", "0014_alter_annotationlabel_analyzer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="analysis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to="analyzer.analysis",
            ),
        ),
    ]
