# Generated by Django 4.2.15 on 2024-09-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0015_alter_annotation_analysis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationlabel",
            name="color",
            field=models.CharField(default="#05313d", max_length=12),
        ),
    ]
