# Generated by Django 4.2.15 on 2024-09-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0016_alter_annotationlabel_color"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="annotationlabel",
            name="Only install one label of given name for each analyzer_id (no duplicates)",
        ),
        migrations.AddConstraint(
            model_name="annotationlabel",
            constraint=models.UniqueConstraint(
                fields=("analyzer", "text", "creator"),
                name="Only install one label of given name for each analyzer_id PER user (no duplicates)",
            ),
        ),
    ]
