# Generated by Django 4.2.16 on 2024-09-29 03:14

from django.db import migrations, models
import opencontractserver.shared.defaults
import opencontractserver.shared.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "annotations",
            "0017_remove_annotationlabel_only_install_one_label_of_given_name_for_each_analyzer_id_no_duplicates__and_",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="label_type",
            field=models.CharField(
                choices=[
                    ("RELATIONSHIP_LABEL", "Relationship label."),
                    ("DOC_TYPE_LABEL", "Document-level type label."),
                    ("TOKEN_LABEL", "Token-level labels for token-based labeling"),
                    ("SPAN_LABEL", "Span labels for span-based labeling"),
                    ("METADATA_LABEL", "Metadata label for manual entry field"),
                ],
                default="TOKEN_LABEL",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="bounding_box",
            field=opencontractserver.shared.fields.NullableJSONField(
                default=opencontractserver.shared.defaults.empty_bounding_box, null=True
            ),
        ),
        migrations.AlterField(
            model_name="annotationlabel",
            name="label_type",
            field=models.CharField(
                choices=[
                    ("RELATIONSHIP_LABEL", "Relationship label."),
                    ("DOC_TYPE_LABEL", "Document-level type label."),
                    ("TOKEN_LABEL", "Token-level labels for token-based labeling"),
                    ("SPAN_LABEL", "Span labels for span-based labeling"),
                    ("METADATA_LABEL", "Metadata label for manual entry field"),
                ],
                default="TOKEN_LABEL",
                max_length=128,
            ),
        ),
    ]
