# Generated by Django 4.2.16 on 2024-09-30 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "annotations",
            "0018_annotation_label_type_alter_annotation_bounding_box_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="annotation",
            old_name="label_type",
            new_name="annotation_type",
        ),
    ]
