# Generated by Django 4.2.16 on 2024-10-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0019_rename_label_type_annotation_annotation_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="annotationlabel",
            name="Only install one label of given name for each analyzer_id PER user (no duplicates)",
        ),
        migrations.AddConstraint(
            model_name="annotationlabel",
            constraint=models.UniqueConstraint(
                fields=("analyzer", "text", "creator", "label_type"),
                name="Only install one label of given name for each analyzer_id PER user (no duplicates)",
            ),
        ),
    ]
