# Generated by Django 4.2.16 on 2024-12-07 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "annotations",
            "0020_remove_annotationlabel_only_install_one_label_of_given_name_for_each_analyzer_id_per_user_no_duplica",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="annotations.annotation",
            ),
        ),
    ]
