# Generated by Django 4.2.16 on 2024-12-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0021_annotation_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="relationship",
            name="structural",
            field=models.BooleanField(default=False),
        ),
    ]
