# Generated by Django 4.2.16 on 2024-12-27 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0011_alter_document_page_count"),
        ("annotations", "0022_relationship_structural"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationship",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationships",
                to="documents.document",
            ),
        ),
    ]
