# Generated by Django 4.2.16 on 2024-12-27 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("corpuses", "0014_alter_corpus_label_set"),
        ("annotations", "0023_alter_relationship_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationship",
            name="corpus",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationships",
                to="corpuses.corpus",
            ),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="relationship_label",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationships",
                to="annotations.annotationlabel",
            ),
        ),
    ]
