# Generated by Django 4.2.16 on 2024-12-27 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0008_alter_analysis_analyzed_corpus"),
        ("annotations", "0024_alter_relationship_corpus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="relationship",
            name="analysis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationships",
                to="analyzer.analysis",
            ),
        ),
    ]
