# Generated by Django 4.2.18 on 2025-01-26 20:13

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0026_note_noteuserobjectpermission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
    ]
