# Generated by Django 4.2.18 on 2025-01-26 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("corpuses", "0014_alter_corpus_label_set"),
        ("annotations", "0027_note_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="corpus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notes",
                to="corpuses.corpus",
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["corpus"], name="annotations_corpus__816064_idx"
            ),
        ),
    ]
