# Generated by Django 4.2.18 on 2025-02-06 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("annotations", "0028_note_corpus_note_annotations_corpus__816064_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
