# Generated by Django 4.2.20 on 2025-03-12 05:55

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0029_alter_note_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=768, null=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=768, null=True),
        ),
    ]
