# Generated by Django 4.2.20 on 2025-05-26 15:31

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        (
            "annotations",
            "0030_embedding_annotation_embeddings_note_embeddings_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=384, null=True
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=384, null=True
            ),
        ),
    ]
