# Generated by Django 4.2.20 on 2025-06-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0031_alter_annotation_embedding_alter_note_embedding"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(
                fields=["structural", "corpus"], name="annotations_structu_54f773_idx"
            ),
        ),
    ]
