# Generated by Django 4.2.20 on 2025-07-25 16:48

from django.db import migrations, models
import opencontractserver.shared.defaults
import opencontractserver.shared.fields


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0033_noterevision"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationlabel",
            name="data_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STRING", "String"),
                    ("TEXT", "Text (Multiline)"),
                    ("BOOLEAN", "Boolean"),
                    ("INTEGER", "Integer"),
                    ("FLOAT", "Float"),
                    ("DATE", "Date"),
                    ("DATETIME", "DateTime"),
                    ("URL", "URL"),
                    ("EMAIL", "Email"),
                    ("CHOICE", "Choice (Select)"),
                    ("MULTI_CHOICE", "Multiple Choice"),
                    ("JSON", "JSON Object"),
                ],
                help_text="Data type for METADATA_LABEL annotations",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="annotationlabel",
            name="metadata_config",
            field=opencontractserver.shared.fields.NullableJSONField(
                blank=True,
                default=opencontractserver.shared.defaults.jsonfield_default_value,
                help_text="Configuration for metadata fields",
                null=True,
            ),
        ),
    ]
