# Generated by Django 3.2.9 on 2023-03-02 04:48

from django.db import migrations, models
import opencontractserver.types.enums


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_create_initial_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexport',
            name='format',
            field=models.CharField(choices=[('LangChain Format', 'LANGCHAIN'), ('Open Contracts Format', 'OPEN_CONTRACTS')], default=opencontractserver.types.enums.ExportType['OPEN_CONTRACTS'], max_length=128),
        ),
    ]
