# Generated by Django 3.2.9 on 2022-06-13 03:17

from django.db import migrations, models
import opencontractserver.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_create_default_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name of User'),
        ),
        migrations.AlterField(
            model_name='userexport',
            name='zip',
            field=models.FileField(blank=True, upload_to=opencontractserver.users.models.calculate_export_filename),
        ),
        migrations.AlterField(
            model_name='userimport',
            name='zip',
            field=models.FileField(blank=True, upload_to=opencontractserver.users.models.calculate_import_filename),
        ),
    ]
