# Generated by Django 3.2.9 on 2023-03-03 06:04

from django.db import migrations, models
import opencontractserver.types.enums


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userexportgroupobjectpermission_userexportuserobjectpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexport',
            name='format',
            field=models.CharField(choices=[('LANGCHAIN', 'LANGCHAIN'), ('OPEN_CONTRACTS', 'OPEN_CONTRACTS')], default=opencontractserver.types.enums.ExportType['OPEN_CONTRACTS'], max_length=128),
        ),
    ]
