# Generated by Django 3.2.9 on 2023-03-04 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userexport_format'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexport',
            old_name='zip',
            new_name='file',
        ),
    ]
