# Generated by Django 4.2.16 on 2025-01-20 07:02

from django.db import migrations, models
import opencontractserver.shared.defaults
import opencontractserver.shared.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_setup_document_row_analysis_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="userexport",
            name="input_kwargs",
            field=opencontractserver.shared.fields.NullableJSONField(
                blank=True,
                default=opencontractserver.shared.defaults.jsonfield_default_value,
                help_text="Additional keyword arguments to pass to post-processors",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userexport",
            name="post_processors",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of fully qualified Python paths to post-processor functions",
            ),
        ),
    ]
