# Generated by Django 4.2.16 on 2025-01-20 17:21

from django.db import migrations, models
import django.utils.timezone
import uuid


def create_installation(apps, schema_editor):
    """Create a singleton installation instance if it doesn't exist. Used for 
    telemetry, if enabled.

    Args:
        apps (_type_): _description_
        schema_editor (_type_): _description_
    """
    Installation = apps.get_model('users', 'Installation')
    if not Installation.objects.exists():
        Installation.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_userexport_input_kwargs_userexport_post_processors"),
    ]

    operations = [
        migrations.CreateModel(
            name="Installation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this installation",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Installation Date",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether telemetry is enabled for this installation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Installation",
                "verbose_name_plural": "Installation",
            },
        ),
        migrations.RunPython(create_installation, reverse_code=migrations.RunPython.noop),
    ]
