# Generated by Django 4.2.20 on 2025-03-08 06:49

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.core.management.sql import emit_post_migrate_signal
from django.conf import settings
import logging

from django.db import migrations

logger = logging.getLogger(__name__)

public_group_permissions = {
    settings.DEFAULT_PERMISSIONS_GROUP: [
        'remove_corpus',
        'remove_document',
        'remove_labelset',
        'remove_annotationlabel',
        'remove_relationship', 
        'remove_annotation',
        'remove_userimport',
        'remove_userexport',
        'remove_gremlinengine',
        'remove_analyzer',
        "remove_corpusaction",
        "remove_chatmessage",
        "remove_chatmessage",
        "remove_documentanalysisrow",
        "remove_corpusquery",
    ]
}


def add_group_permissions(apps, schema_editor):

    # See https://code.djangoproject.com/ticket/23422
    db_alias = schema_editor.connection.alias

    try:
        emit_post_migrate_signal(2, False, 'default')
    except TypeError:  # Django < 1.8
        emit_post_migrate_signal([], 2, False, 'default', db_alias)

    for group in public_group_permissions:
        role, created = Group.objects.get_or_create(name=group)
        logger.info(f'{group} Group created')
        for perm in public_group_permissions[group]:
            logger.info(f'Permitting {group} to {perm}')
            role.permissions.add(Permission.objects.get(codename=perm))
        role.save()

    logger.info("Installation of default public access group COMPLETE!")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_auto_20250224_0600"),
    ]

    operations = [
        migrations.RunPython(add_group_permissions),
    ]
