# Generated by Django 4.2.20 on 2025-08-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_auto_20250224_0600"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="slug",
            field=models.CharField(
                blank=True,
                help_text="Case-sensitive URL slug. Allowed characters: A-Z, a-z, 0-9, and hyphen (-).",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
