# Generated by Django 3.2.9 on 2024-05-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='match_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='column',
            name='query',
            field=models.TextField(blank=True, null=True),
        ),
    ]
