# Generated by Django 3.2.9 on 2024-06-02 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpuses', '0002_initial'),
        ('documents', '0005_document_embedding'),
        ('extracts', '0002_auto_20240602_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='extract',
            name='docs',
            field=models.ManyToManyField(blank=True, related_name='extracts', related_query_name='extract', to='documents.Document'),
        ),
        migrations.AlterField(
            model_name='extract',
            name='corpus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extracts', to='corpuses.corpus'),
        ),
    ]
