# Generated by Django 3.2.9 on 2024-06-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracts', '0004_alter_extract_corpus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extract',
            old_name='docs',
            new_name='documents',
        ),
        migrations.AddField(
            model_name='extract',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
