# Generated by Django 3.2.9 on 2024-06-02 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extracts', '0005_auto_20240602_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extract',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='fieldset',
            name='owner',
        ),
    ]
