# Generated by Django 3.2.9 on 2024-06-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracts', '0007_auto_20240606_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='extract_is_list',
            field=models.BooleanField(default=False),
        ),
    ]
