# Generated by Django 3.2.9 on 2024-06-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracts', '0008_column_extract_is_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='must_contain_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
