# Generated by Django 3.2.9 on 2024-06-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0006_annotation_embedding'),
        ('extracts', '0009_column_must_contain_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacell',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='referencing_cells', related_query_name='referencing_cell', to='annotations.Annotation'),
        ),
    ]
