# Generated by Django 3.2.9 on 2024-06-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extracts', '0010_datacell_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='task_name',
            field=models.CharField(default='opencontractserver.tasks.data_extract_tasks.oc_llama_index_doc_query', max_length=1024),
        ),
    ]
