# Generated by Django 3.2.9 on 2024-06-22 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extracts', '0011_column_task_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='languagemodelgroupobjectpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='languagemodelgroupobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='languagemodelgroupobjectpermission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='languagemodelgroupobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='languagemodeluserobjectpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='languagemodeluserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='languagemodeluserobjectpermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='languagemodeluserobjectpermission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='column',
            name='language_model',
        ),
        migrations.DeleteModel(
            name='LanguageModel',
        ),
        migrations.DeleteModel(
            name='LanguageModelGroupObjectPermission',
        ),
        migrations.DeleteModel(
            name='LanguageModelUserObjectPermission',
        ),
    ]
