# Generated by Django 4.2.16 on 2024-11-03 21:06

from django.db import migrations
import opencontractserver.shared.fields


class Migration(migrations.Migration):

    dependencies = [
        ("extracts", "0014_extract_corpus_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datacell",
            name="corrected_data",
            field=opencontractserver.shared.fields.NullableJSONField(
                blank=True, default=None, null=True
            ),
        ),
    ]
