# Generated by Django 4.2.20 on 2025-07-06 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extracts", "0015_alter_datacell_corrected_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="column",
            name="agentic",
        ),
    ]
