# Generated by Django 4.2.20 on 2025-07-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extracts", "0016_remove_column_agentic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="column",
            name="task_name",
            field=models.CharField(
                default="opencontractserver.tasks.data_extract_tasks.doc_extract_query_task",
                max_length=1024,
            ),
        ),
    ]
