# Generated by Django 4.2.20 on 2025-08-09 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extracts", "0018_add_metadata_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="column",
            new_name="extracts_co_fieldse_9e265e_idx",
            old_name="extracts_co_fieldse_c5f8d1_idx",
        ),
        migrations.RenameIndex(
            model_name="column",
            new_name="extracts_co_is_manu_f49790_idx",
            old_name="extracts_co_is_manu_7b8e9f_idx",
        ),
    ]
