# Generated by Django 4.2.16 on 2024-09-15 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userfeedback",
            options={
                "permissions": (
                    ("permission_userfeedback", "permission UserFeedback"),
                    ("publish_userfeedback", "publish UserFeedback"),
                    ("create_userfeedback", "create UserFeedback"),
                    ("read_userfeedback", "read UserFeedback"),
                    ("update_userfeedback", "update UserFeedback"),
                    ("remove_userfeedback", "delete UserFeedback"),
                )
            },
        ),
    ]
