# Generated by Django 4.2.16 on 2024-09-15 20:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedback", "0003_alter_userfeedback_commented_annotation"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserFeedbackObjectPermission",
            new_name="UserFeedbackUserObjectPermission",
        ),
    ]
