# Generated by Django 3.2.9 on 2022-06-13 03:17

from django.db import migrations, models
import opencontractserver.corpuses.models


class Migration(migrations.Migration):

    dependencies = [
        ('corpuses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=opencontractserver.corpuses.models.calculate_icon_filepath),
        ),
    ]
