# Generated by Django 3.2.9 on 2024-06-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0006_annotation_embedding'),
        ('corpuses', '0005_alter_corpusquery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpusquery',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='queries', related_query_name='created_by_query', to='annotations.Annotation'),
        ),
    ]
