# Generated by Django 3.2.9 on 2024-07-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpuses', '0006_alter_corpusquery_sources'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='corpus',
            index=models.Index(fields=['title'], name='corpuses_co_title_3c42f5_idx'),
        ),
        migrations.AddIndex(
            model_name='corpus',
            index=models.Index(fields=['label_set'], name='corpuses_co_label_s_d51247_idx'),
        ),
        migrations.AddIndex(
            model_name='corpus',
            index=models.Index(fields=['creator'], name='corpuses_co_creator_2c49a2_idx'),
        ),
        migrations.AddIndex(
            model_name='corpus',
            index=models.Index(fields=['user_lock'], name='corpuses_co_user_lo_e254ea_idx'),
        ),
        migrations.AddIndex(
            model_name='corpus',
            index=models.Index(fields=['created'], name='corpuses_co_created_e1f50a_idx'),
        ),
        migrations.AddIndex(
            model_name='corpus',
            index=models.Index(fields=['modified'], name='corpuses_co_modifie_b75acf_idx'),
        ),
    ]
