# Generated by Django 3.2.9 on 2024-07-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpuses', '0007_auto_20240722_0715'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='corpusquery',
            index=models.Index(fields=['corpus'], name='corpuses_co_corpus__4f154d_idx'),
        ),
        migrations.AddIndex(
            model_name='corpusquery',
            index=models.Index(fields=['started'], name='corpuses_co_started_98096f_idx'),
        ),
        migrations.AddIndex(
            model_name='corpusquery',
            index=models.Index(fields=['completed'], name='corpuses_co_complet_4ac647_idx'),
        ),
        migrations.AddIndex(
            model_name='corpusquery',
            index=models.Index(fields=['failed'], name='corpuses_co_failed_e3e0fc_idx'),
        ),
        migrations.AddIndex(
            model_name='corpusquery',
            index=models.Index(fields=['creator'], name='corpuses_co_creator_050962_idx'),
        ),
        migrations.AddIndex(
            model_name='corpusquery',
            index=models.Index(fields=['created'], name='corpuses_co_created_31e32b_idx'),
        ),
    ]
