# Generated by Django 4.2.14 on 2024-08-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpuses", "0010_corpusaction_corpusactionuserobjectpermission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="corpusaction",
            name="name",
            field=models.CharField(default="Corpus Action", max_length=256),
        ),
        migrations.AlterField(
            model_name="corpusaction",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("add_document", "Add Document"),
                    ("edit_document", "Edit Document"),
                ],
                max_length=256,
            ),
        ),
    ]
