# Generated by Django 4.2.16 on 2024-09-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpuses", "0012_corpusaction_disabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="corpus",
            name="allow_comments",
            field=models.BooleanField(default=False),
        ),
    ]
