# Generated by Django 4.2.20 on 2025-03-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpuses", "0015_corpus_post_processors"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="corpusaction",
            options={
                "permissions": (
                    ("permission_corpusaction", "permission corpusaction"),
                    ("publish_corpusaction", "publish corpusaction"),
                    ("create_corpusaction", "create corpusaction"),
                    ("read_corpusaction", "read corpusaction"),
                    ("update_corpusaction", "update corpusaction"),
                    ("remove_corpusaction", "delete corpusaction"),
                )
            },
        ),
        migrations.AddField(
            model_name="corpus",
            name="preferred_embedder",
            field=models.CharField(
                blank=True,
                help_text="Fully qualified Python path to the embedder class to use for this corpus",
                max_length=256,
                null=True,
            ),
        ),
    ]
