# Generated by Django 4.2.20 on 2025-03-12 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corpuses", "0015_corpus_post_processors"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="corpusaction",
            options={
                "permissions": (
                    ("permission_corpusaction", "permission corpusaction"),
                    ("publish_corpusaction", "publish corpusaction"),
                    ("create_corpusaction", "create corpusaction"),
                    ("read_corpusaction", "read corpusaction"),
                    ("update_corpusaction", "update corpusaction"),
                    ("remove_corpusaction", "delete corpusaction"),
                )
            },
        ),
    ]
