# Generated by Django 4.2.20 on 2025-03-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpuses", "0016_alter_corpusaction_options_corpus_preferred_embedder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corpus",
            name="preferred_embedder",
            field=models.CharField(
                blank=True,
                help_text="Fully qualified Python path to the embedder class to use for this corpus",
                max_length=1024,
                null=True,
            ),
        ),
    ]
