# Generated by Django 4.2.20 on 2025-08-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpuses", "0018_corpus_md_description_corpusdescriptionrevision"),
    ]

    operations = [
        migrations.AddField(
            model_name="corpus",
            name="slug",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Case-sensitive slug unique per creator. Allowed: A-Z, a-z, 0-9, hyphen (-).",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="corpus",
            constraint=models.UniqueConstraint(
                fields=("creator", "slug"), name="uniq_corpus_slug_per_creator_cs"
            ),
        ),
    ]
