# Generated by Django 3.2.9 on 2022-06-13 03:17

from django.db import migrations, models
import functools
import opencontractserver.shared.utils


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='icon',
            field=models.FileField(blank=True, max_length=1024, upload_to=functools.partial(opencontractserver.shared.utils.calc_oc_file_path, *(), **{'sub_folder': 'pdf_icons'})),
        ),
        migrations.AlterField(
            model_name='document',
            name='pawls_parse_file',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=functools.partial(opencontractserver.shared.utils.calc_oc_file_path, *(), **{'sub_folder': 'pawls_layers_files'})),
        ),
        migrations.AlterField(
            model_name='document',
            name='pdf_file',
            field=models.FileField(max_length=1024, upload_to=functools.partial(opencontractserver.shared.utils.calc_oc_file_path, *(), **{'sub_folder': 'pdf_files'})),
        ),
        migrations.AlterField(
            model_name='document',
            name='txt_extract_file',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=functools.partial(opencontractserver.shared.utils.calc_oc_file_path, *(), **{'sub_folder': 'txt_layers_files'})),
        ),
    ]
