# Generated by Django 3.2.9 on 2024-07-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_embedding'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['title'], name='documents_d_title_ccf306_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['page_count'], name='documents_d_page_co_e88d38_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['creator'], name='documents_d_creator_a6b2c0_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created'], name='documents_d_created_f84812_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['modified'], name='documents_d_modifie_b15cc7_idx'),
        ),
    ]
