# Generated by Django 4.2.16 on 2024-09-29 06:44

from django.db import migrations, models
import functools
import opencontractserver.shared.utils


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0009_document_file_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="processing_finished",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="processing_started",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                max_length=1024,
                null=True,
                upload_to=functools.partial(
                    opencontractserver.shared.utils.calc_oc_file_path,
                    *(),
                    **{"sub_folder": "pdf_files"}
                ),
            ),
        ),
    ]
