# Generated by Django 4.2.16 on 2024-10-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0010_document_processing_finished_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="page_count",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
