# Generated by Django 4.2.18 on 2025-01-25 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("corpuses", "0014_alter_corpus_label_set"),
        ("documents", "0012_documentrelationship_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentrelationship",
            name="corpus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_relationships",
                to="corpuses.corpus",
            ),
        ),
    ]
