# Generated by Django 4.2.18 on 2025-01-26 22:48

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0012_document_md_summary_file_documentrelationship_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=384, null=True
            ),
        ),
    ]
