# Generated by Django 4.2.18 on 2025-01-25 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0013_documentrelationship_corpus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="documentrelationship",
            old_name="nodes",
            new_name="data",
        ),
    ]
