# Generated by Django 4.2.18 on 2025-02-03 01:49

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0013_alter_document_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="description_embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=384, null=True
            ),
        ),
    ]
