# Generated by Django 4.2.20 on 2025-03-12 05:55

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0014_document_description_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="description_embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=768, null=True
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=768, null=True
            ),
        ),
    ]
