# Generated by Django 4.2.20 on 2025-03-16 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0014_document_description_embedding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="description_embedding",
        ),
    ]
