import { SemanticICONS } from "semantic-ui-react/dist/commonjs/generic";

export const icons: SemanticICONS[] = [
  "500px",
  "accessible",
  "accusoft",
  "add",
  "add circle",
  "add square",
  "add to calendar",
  "add to cart",
  "add user",
  "address book",
  "address book outline",
  "address card",
  "address card outline",
  "adjust",
  "adn",
  "adversal",
  "affiliatetheme",
  "alarm",
  "alarm mute",
  "ald",
  "algolia",
  "align center",
  "align justify",
  "align left",
  "align right",
  "als",
  "amazon",
  "amazon pay",
  "ambulance",
  "american sign language interpreting",
  "amilia",
  "anchor",
  "android",
  "angellist",
  "angle double down",
  "angle double left",
  "angle double right",
  "angle double up",
  "angle down",
  "angle left",
  "angle right",
  "angle up",
  "angrycreative",
  "angular",
  "announcement",
  "app store",
  "app store ios",
  "apper",
  "apple",
  "apple pay",
  "archive",
  "area chart",
  "area graph",
  "arrow alternate circle down",
  "arrow alternate circle down outline",
  "arrow alternate circle left",
  "arrow alternate circle left outline",
  "arrow alternate circle right",
  "arrow alternate circle right outline",
  "arrow alternate circle up",
  "arrow alternate circle up outline",
  "arrow circle down",
  "arrow circle left",
  "arrow circle right",
  "arrow circle up",
  "arrow down",
  "arrow down cart",
  "arrow left",
  "arrow right",
  "arrow up",
  "arrows alternate",
  "arrows alternate horizontal",
  "arrows alternate vertical",
  "asexual",
  "asl",
  "asl interpreting",
  "assistive listening devices",
  "assistive listening systems",
  "asterisk",
  "asymmetrik",
  "at",
  "attach",
  "attention",
  "audible",
  "audio description",
  "autoprefixer",
  "avianex",
  "aviato",
  "aws",
  "backward",
  "balance",
  "balance scale",
  "ban",
  "band aid",
  "bandcamp",
  "bar",
  "barcode",
  "bars",
  "baseball ball",
  "basketball ball",
  "bath",
  "bathtub",
  "battery empty",
  "battery four",
  "battery full",
  "battery half",
  "battery high",
  "battery low",
  "battery one",
  "battery quarter",
  "battery three",
  "battery three quarters",
  "battery two",
  "battery zero",
  "bed",
  "beer",
  "behance",
  "behance square",
  "bell",
  "bell outline",
  "bell slash",
  "bell slash outline",
  "bicycle",
  "bimobject",
  "binoculars",
  "birthday",
  "birthday cake",
  "bitbucket",
  "bitbucket square",
  "bitcoin",
  "bity",
  "black tie",
  "blackberry",
  "blind",
  "block layout",
  "blogger",
  "blogger b",
  "bluetooth",
  "bluetooth alternative",
  "bluetooth b",
  "bold",
  "bolt",
  "bomb",
  "book",
  "bookmark",
  "bookmark outline",
  "bowling ball",
  "box",
  "boxes",
  "braille",
  "briefcase",
  "broken chain",
  "browser",
  "btc",
  "bug",
  "building",
  "building outline",
  "bullhorn",
  "bullseye",
  "buromobelexperte",
  "bus",
  "buysellads",
  "calculator",
  "calendar",
  "calendar alternate",
  "calendar alternate outline",
  "calendar check",
  "calendar check outline",
  "calendar minus",
  "calendar minus outline",
  "calendar outline",
  "calendar plus",
  "calendar plus outline",
  "calendar times",
  "calendar times outline",
  "call",
  "call square",
  "camera",
  "camera retro",
  "cancel",
  "car",
  "caret down",
  "caret left",
  "caret right",
  "caret square down",
  "caret square down outline",
  "caret square left",
  "caret square left outline",
  "caret square right",
  "caret square right outline",
  "caret square up",
  "caret square up outline",
  "caret up",
  "cart",
  "cart arrow down",
  "cart plus",
  "cc",
  "cc amazon pay",
  "cc amex",
  "cc apple pay",
  "cc diners club",
  "cc discover",
  "cc jcb",
  "cc mastercard",
  "cc paypal",
  "cc stripe",
  "cc visa",
  "centercode",
  "certificate",
  "chain",
  "chart area",
  "chart bar",
  "chart bar outline",
  "chart line",
  "chart pie",
  "chat",
  "check",
  "check circle",
  "check circle outline",
  "check square",
  "check square outline",
  "checked calendar",
  "checkmark",
  "checkmark box",
  "chess",
  "chess bishop",
  "chess board",
  "chess king",
  "chess knight",
  "chess pawn",
  "chess queen",
  "chess rock",
  "chess rook",
  "chevron circle down",
  "chevron circle left",
  "chevron circle right",
  "chevron circle up",
  "chevron down",
  "chevron left",
  "chevron right",
  "chevron up",
  "child",
  "chrome",
  "circle",
  "circle notch",
  "circle notched",
  "circle outline",
  "circle thin",
  "clipboard",
  "clipboard check",
  "clipboard list",
  "clipboard outline",
  "clock",
  "clock outline",
  "clone",
  "clone outline",
  "close",
  "closed captioning",
  "closed captioning outline",
  "cloud",
  "cloud download",
  "cloud upload",
  "cloudscale",
  "cloudsmith",
  "cloudversify",
  "cny",
  "cocktail",
  "code",
  "code branch",
  "codepen",
  "codiepie",
  "coffee",
  "cog",
  "cogs",
  "columns",
  "comment",
  "comment alternate",
  "comment alternate outline",
  "comment outline",
  "commenting",
  "comments",
  "comments outline",
  "compass",
  "compass outline",
  "compose",
  "compress",
  "computer",
  "configure",
  "connectdevelop",
  "contao",
  "content",
  "conversation",
  "copy",
  "copy outline",
  "copyright",
  "copyright outline",
  "cpanel",
  "creative commons",
  "credit card",
  "credit card alternative",
  "credit card outline",
  "crop",
  "crosshairs",
  "css3",
  "css3 alternate",
  "cube",
  "cubes",
  "currency",
  "cut",
  "cuttlefish",
  "dashboard",
  "dashcube",
  "database",
  "deaf",
  "deafness",
  "delete",
  "delete calendar",
  "delicious",
  "deploydog",
  "deskpro",
  "desktop",
  "detective",
  "deviantart",
  "diamond",
  "digg",
  "digital ocean",
  "discord",
  "discourse",
  "discussions",
  "disk",
  "dna",
  "dochub",
  "docker",
  "doctor",
  "dollar",
  "dollar sign",
  "dolly",
  "dolly flatbed",
  "dont",
  "dot circle",
  "dot circle outline",
  "download",
  "draft2digital",
  "dribbble",
  "dribbble square",
  "drivers license",
  "dropbox",
  "dropdown",
  "drupal",
  "dyalog",
  "earlybirds",
  "edge",
  "edit",
  "edit outline",
  "eject",
  "elementor",
  "ellipsis horizontal",
  "ellipsis vertical",
  "ember",
  "emergency",
  "empire",
  "envelope",
  "envelope open",
  "envelope open outline",
  "envelope outline",
  "envelope square",
  "envira",
  "envira gallery",
  "erase",
  "eraser",
  "erlang",
  "ethereum",
  "etsy",
  "eur",
  "euro",
  "euro sign",
  "exchange",
  "exclamation",
  "exclamation circle",
  "exclamation triangle",
  "expand",
  "expand arrows alternate",
  "expeditedssl",
  "external",
  "external alternate",
  "external share",
  "external square",
  "external square alternate",
  "eye",
  "eye dropper",
  "eye slash",
  "eye slash outline",
  "eyedropper",
  "facebook",
  "facebook f",
  "facebook messenger",
  "facebook official",
  "facebook square",
  "factory",
  "fast backward",
  "fast forward",
  "favorite",
  "fax",
  "feed",
  "female",
  "female homosexual",
  "fighter jet",
  "file",
  "file alternate",
  "file alternate outline",
  "file archive",
  "file archive outline",
  "file audio",
  "file audio outline",
  "file code",
  "file code outline",
  "file excel",
  "file excel outline",
  "file image",
  "file image outline",
  "file outline",
  "file pdf",
  "file pdf outline",
  "file powerpoint",
  "file powerpoint outline",
  "file text",
  "file text outline",
  "file video",
  "file video outline",
  "file word",
  "file word outline",
  "film",
  "filter",
  "find",
  "fire",
  "fire extinguisher",
  "firefox",
  "first aid",
  "first order",
  "firstdraft",
  "flag",
  "flag checkered",
  "flag outline",
  "flask",
  "flickr",
  "flipboard",
  "fly",
  "folder",
  "folder open",
  "folder open outline",
  "folder outline",
  "font",
  "font awesome",
  "font awesome alternate",
  "font awesome flag",
  "fonticons",
  "fonticons fi",
  "food",
  "football ball",
  "fork",
  "fort awesome",
  "fort awesome alternate",
  "forumbee",
  "forward",
  "foursquare",
  "free code camp",
  "freebsd",
  "frown",
  "frown outline",
  "futbol",
  "futbol outline",
  "game",
  "gamepad",
  "gavel",
  "gay",
  "gbp",
  "gem",
  "gem outline",
  "genderless",
  "get pocket",
  "gg",
  "gg circle",
  "gift",
  "git",
  "git square",
  "github",
  "github alternate",
  "github square",
  "gitkraken",
  "gitlab",
  "gitter",
  "glass martini",
  "glide",
  "glide g",
  "globe",
  "gofore",
  "golf ball",
  "goodreads",
  "goodreads g",
  "google",
  "google drive",
  "google play",
  "google plus",
  "google plus circle",
  "google plus g",
  "google plus official",
  "google plus square",
  "google wallet",
  "grab",
  "graduation",
  "graduation cap",
  "gratipay",
  "grav",
  "grid layout",
  "gripfire",
  "group",
  "grunt",
  "gulp",
  "h",
  "h square",
  "hacker news",
  "hacker news square",
  "hand lizard",
  "hand lizard outline",
  "hand paper",
  "hand paper outline",
  "hand peace",
  "hand peace outline",
  "hand point down",
  "hand point down outline",
  "hand point left",
  "hand point left outline",
  "hand point right",
  "hand point right outline",
  "hand point up",
  "hand point up outline",
  "hand pointer",
  "hand pointer outline",
  "hand rock",
  "hand rock outline",
  "hand scissors",
  "hand scissors outline",
  "hand spock",
  "hand spock outline",
  "hand victory",
  "handicap",
  "handshake",
  "handshake outline",
  "hard of hearing",
  "hashtag",
  "hdd",
  "hdd outline",
  "header",
  "heading",
  "headphones",
  "heart",
  "heart outline",
  "heartbeat",
  "help",
  "help circle",
  "heterosexual",
  "hide",
  "hips",
  "hire a helper",
  "history",
  "hockey puck",
  "home",
  "hooli",
  "hospital",
  "hospital outline",
  "hospital symbol",
  "hotel",
  "hotjar",
  "hourglass",
  "hourglass end",
  "hourglass four",
  "hourglass full",
  "hourglass half",
  "hourglass one",
  "hourglass outline",
  "hourglass start",
  "hourglass three",
  "hourglass two",
  "hourglass zero",
  "houzz",
  "html5",
  "hubspot",
  "i cursor",
  "id badge",
  "id badge outline",
  "id card",
  "id card outline",
  "idea",
  "ils",
  "image",
  "image outline",
  "images",
  "images outline",
  "imdb",
  "in cart",
  "inbox",
  "indent",
  "industry",
  "info",
  "info circle",
  "inr",
  "instagram",
  "intergender",
  "internet explorer",
  "intersex",
  "ioxhost",
  "italic",
  "itunes",
  "itunes note",
  "jenkins",
  "joget",
  "joomla",
  "jpy",
  "js",
  "js square",
  "jsfiddle",
  "key",
  "keyboard",
  "keyboard outline",
  "keycdn",
  "kickstarter",
  "kickstarter k",
  "korvue",
  "krw",
  "lab",
  "language",
  "laptop",
  "laravel",
  "lastfm",
  "lastfm square",
  "law",
  "leaf",
  "leanpub",
  "legal",
  "lemon",
  "lemon outline",
  "lesbian",
  "less",
  "level down",
  "level down alternate",
  "level up",
  "level up alternate",
  "life ring",
  "life ring outline",
  "lightbulb",
  "lightbulb outline",
  "lightning",
  "like",
  "line graph",
  "linechat",
  "linkedin",
  "linkedin alternate",
  "linkedin square",
  "linkify",
  "linode",
  "linux",
  "lira",
  "lira sign",
  "list",
  "list alternate",
  "list alternate outline",
  "list layout",
  "list ol",
  "list ul",
  "location arrow",
  "lock",
  "lock open",
  "log out",
  "long arrow alternate down",
  "long arrow alternate left",
  "long arrow alternate right",
  "long arrow alternate up",
  "low vision",
  "lyft",
  "magento",
  "magic",
  "magnet",
  "magnify",
  "mail",
  "mail forward",
  "mail outline",
  "mail square",
  "male",
  "male homosexual",
  "man",
  "map",
  "map marker",
  "map marker alternate",
  "map outline",
  "map pin",
  "map signs",
  "marker",
  "mars",
  "mars alternate",
  "mars double",
  "mars horizontal",
  "mars stroke",
  "mars stroke horizontal",
  "mars stroke vertical",
  "mars vertical",
  "maxcdn",
  "meanpath",
  "medapps",
  "medium",
  "medium m",
  "medkit",
  "medrt",
  "meetup",
  "meh",
  "meh outline",
  "mercury",
  "microchip",
  "microphone",
  "microphone slash",
  "microsoft",
  "microsoft edge",
  "military",
  "minus",
  "minus circle",
  "minus square",
  "minus square outline",
  "mix",
  "mixcloud",
  "mizuni",
  "mobile",
  "mobile alternate",
  "modx",
  "monero",
  "money",
  "money bill alternate",
  "money bill alternate outline",
  "moon",
  "moon outline",
  "motorcycle",
  "mouse pointer",
  "move",
  "ms edge",
  "music",
  "mute",
  "napster",
  "neuter",
  "new pied piper",
  "newspaper",
  "newspaper outline",
  "nintendo switch",
  "node",
  "node js",
  "non binary transgender",
  "npm",
  "ns8",
  "numbered list",
  "nutritionix",
  "object group",
  "object group outline",
  "object ungroup",
  "object ungroup outline",
  "odnoklassniki",
  "odnoklassniki square",
  "opencart",
  "openid",
  "opera",
  "optin monster",
  "options",
  "ordered list",
  "osi",
  "other gender",
  "other gender horizontal",
  "other gender vertical",
  "outdent",
  "page4",
  "pagelines",
  "paint brush",
  "palfed",
  "pallet",
  "paper plane",
  "paper plane outline",
  "paperclip",
  "paragraph",
  "paste",
  "patreon",
  "pause",
  "pause circle",
  "pause circle outline",
  "paw",
  "payment",
  "paypal",
  "paypal card",
  "pen square",
  "pencil",
  "pencil alternate",
  "pencil square",
  "percent",
  "periscope",
  "phabricator",
  "phoenix framework",
  "phone",
  "phone square",
  "phone volume",
  "photo",
  "php",
  "picture",
  "pie chart",
  "pie graph",
  "pied piper",
  "pied piper alternate",
  "pied piper hat",
  "pied piper pp",
  "pills",
  "pin",
  "pinterest",
  "pinterest p",
  "pinterest square",
  "plane",
  "play",
  "play circle",
  "play circle outline",
  "playstation",
  "plug",
  "plus",
  "plus cart",
  "plus circle",
  "plus square",
  "plus square outline",
  "podcast",
  "point",
  "pointing down",
  "pointing left",
  "pointing right",
  "pointing up",
  "pound",
  "pound sign",
  "power",
  "power cord",
  "power off",
  "print",
  "privacy",
  "product hunt",
  "protect",
  "pushed",
  "puzzle",
  "puzzle piece",
  "python",
  "qq",
  "qrcode",
  "question",
  "question circle",
  "question circle outline",
  "quidditch",
  "quinscape",
  "quora",
  "quote left",
  "quote right",
  "r circle",
  "radio",
  "rain",
  "random",
  "ravelry",
  "react",
  "rebel",
  "record",
  "recycle",
  "reddit",
  "reddit alien",
  "reddit square",
  "redo",
  "redo alternate",
  "redriver",
  "refresh",
  "registered",
  "registered outline",
  "remove",
  "remove bookmark",
  "remove circle",
  "remove from calendar",
  "remove user",
  "rendact",
  "renren",
  "repeat",
  "reply",
  "reply all",
  "replyd",
  "resize horizontal",
  "resize vertical",
  "resolving",
  "retweet",
  "rmb",
  "road",
  "rocket",
  "rocketchat",
  "rockrms",
  "rouble",
  "rss",
  "rss square",
  "rub",
  "ruble",
  "ruble sign",
  "rupee",
  "rupee sign",
  "s15",
  "safari",
  "sass",
  "save",
  "save outline",
  "schlix",
  "scribd",
  "search",
  "search minus",
  "search plus",
  "searchengin",
  "selected radio",
  "sellcast",
  "sellsy",
  "send",
  "server",
  "servicestack",
  "setting",
  "settings",
  "share",
  "share alternate",
  "share alternate square",
  "share square",
  "share square outline",
  "shekel",
  "shekel sign",
  "sheqel",
  "shield",
  "shield alternate",
  "ship",
  "shipping",
  "shipping fast",
  "shirtsinbulk",
  "shop",
  "shopping bag",
  "shopping basket",
  "shopping cart",
  "shower",
  "shuffle",
  "shutdown",
  "sidebar",
  "sign in",
  "sign in alternate",
  "sign language",
  "sign out",
  "sign out alternate",
  "sign-in",
  "sign-in alternate",
  "sign-out",
  "sign-out alternate",
  "signal",
  "signing",
  "signup",
  "simplybuilt",
  "sistrix",
  "sitemap",
  "skyatlas",
  "skype",
  "slack",
  "slack hash",
  "sliders",
  "sliders horizontal",
  "slideshare",
  "smile",
  "smile outline",
  "snapchat",
  "snapchat ghost",
  "snapchat square",
  "snowflake",
  "snowflake outline",
  "soccer",
  "sort",
  "sort alphabet ascending",
  "sort alphabet descending",
  "sort alphabet down",
  "sort alphabet up",
  "sort amount down",
  "sort amount up",
  "sort ascending",
  "sort content ascending",
  "sort content descending",
  "sort descending",
  "sort down",
  "sort numeric ascending",
  "sort numeric descending",
  "sort numeric down",
  "sort numeric up",
  "sort up",
  "sound",
  "soundcloud",
  "space shuttle",
  "speakap",
  "spinner",
  "spoon",
  "spotify",
  "spy",
  "square",
  "square full",
  "square outline",
  "stack exchange",
  "stack overflow",
  "star",
  "star half",
  "star half empty",
  "star half full",
  "star half outline",
  "star outline",
  "staylinked",
  "steam",
  "steam square",
  "steam symbol",
  "step backward",
  "step forward",
  "stethoscope",
  "sticker mule",
  "sticky note",
  "sticky note outline",
  "stop",
  "stop circle",
  "stop circle outline",
  "stopwatch",
  "strava",
  "street view",
  "strikethrough",
  "stripe",
  "stripe card",
  "stripe s",
  "student",
  "studiovinari",
  "stumbleupon",
  "stumbleupon circle",
  "subscript",
  "subway",
  "suitcase",
  "sun",
  "sun outline",
  "superpowers",
  "superscript",
  "supple",
  "sync",
  "sync alternate",
  "syringe",
  "table",
  "table tennis",
  "tablet",
  "tablet alternate",
  "tachometer alternate",
  "tag",
  "tags",
  "talk",
  "target",
  "tasks",
  "taxi",
  "telegram",
  "telegram plane",
  "teletype",
  "television",
  "tencent weibo",
  "terminal",
  "text cursor",
  "text height",
  "text telephone",
  "text width",
  "th",
  "th large",
  "th list",
  "theme",
  "themeisle",
  "thermometer",
  "thermometer empty",
  "thermometer full",
  "thermometer half",
  "thermometer quarter",
  "thermometer three quarters",
  "thumb tack",
  "thumbs down",
  "thumbs down outline",
  "thumbs up",
  "thumbs up outline",
  "thumbtack",
  "ticket",
  "ticket alternate",
  "time",
  "times",
  "times circle",
  "times circle outline",
  "times rectangle",
  "tint",
  "tm",
  "toggle down",
  "toggle left",
  "toggle off",
  "toggle on",
  "toggle right",
  "toggle up",
  "trademark",
  "train",
  "transgender",
  "transgender alternate",
  "translate",
  "trash",
  "trash alternate",
  "trash alternate outline",
  "travel",
  "treatment",
  "tree",
  "trello",
  "triangle down",
  "triangle left",
  "triangle right",
  "triangle up",
  "tripadvisor",
  "trophy",
  "truck",
  "try",
  "tty",
  "tumblr",
  "tumblr square",
  "tv",
  "twitch",
  "twitter",
  "twitter square",
  "typo3",
  "uber",
  "uikit",
  "umbrella",
  "underline",
  "undo",
  "undo alternate",
  "unhide",
  "uniregistry",
  "universal access",
  "university",
  "unlink",
  "unlinkify",
  "unlock",
  "unlock alternate",
  "unmute",
  "unordered list",
  "untappd",
  "upload",
  "usb",
  "usd",
  "user",
  "user cancel",
  "user circle",
  "user circle outline",
  "user close",
  "user delete",
  "user doctor",
  "user md",
  "user outline",
  "user plus",
  "user secret",
  "user times",
  "user x",
  "users",
  "ussunnah",
  "utensil spoon",
  "utensils",
  "vaadin",
  "vcard",
  "venus",
  "venus double",
  "venus mars",
  "viacoin",
  "viadeo",
  "viadeo square",
  "viber",
  "video",
  "video camera",
  "video play",
  "vimeo",
  "vimeo square",
  "vimeo v",
  "vine",
  "vk",
  "vnv",
  "volleyball ball",
  "volume control phone",
  "volume down",
  "volume off",
  "volume up",
  "vuejs",
  "wait",
  "warehouse",
  "warning",
  "warning circle",
  "warning sign",
  "wechat",
  "weibo",
  "weight",
  "weixin",
  "whatsapp",
  "whatsapp square",
  "wheelchair",
  "whmcs",
  "wi-fi",
  "wifi",
  "wikipedia w",
  "window close",
  "window close outline",
  "window maximize",
  "window maximize outline",
  "window minimize",
  "window minimize outline",
  "window restore",
  "window restore outline",
  "windows",
  "winner",
  "wizard",
  "woman",
  "won",
  "won sign",
  "wordpress",
  "wordpress beginner",
  "wordpress forms",
  "wordpress simple",
  "world",
  "wpbeginner",
  "wpexplorer",
  "wpforms",
  "wrench",
  "write",
  "write square",
  "x",
  "xbox",
  "xing",
  "xing square",
  "y combinator",
  "yahoo",
  "yandex",
  "yandex international",
  "yelp",
  "yen",
  "yen sign",
  "yoast",
  "youtube",
  "youtube play",
  "youtube square",
  "zip",
  "zoom",
  "zoom in",
  "zoom out",
  "zoom-in",
  "zoom-out",
];
