"""Tests for corpus groups + cross-corpus retrieval (issue #2056).

Covers, in one place:

* ``CorpusGroup`` model behaviour (slug auto-generation).
* ``CorpusGroupService`` — group visibility, IDOR-safe lookup, the
  call-time ``MIN(corpus_permission, group_membership)`` member-corpus
  gate, and CRUD authorisation.
* The ``search_across_corpora`` agent tool — per-user visibility
  filtering, call-time membership resolution, per-corpus fault isolation,
  clamping, and snippet bounding (vector store faked; the store's own
  search behaviour is covered by ``test_django_annotation_vector_store``).
* The GraphQL surface — permission boundaries on queries + mutations.

Row-level ``user_can`` / ``visible_to_user`` equivalence for the group row
itself is pinned in
``opencontractserver/tests/permissioning/test_authorization_invariants.py``
(``CorpusGroupAuthorizationInvariantsTestCase``).
"""

from __future__ import annotations

from unittest.mock import patch

from asgiref.sync import async_to_sync
from django.contrib.auth.models import AnonymousUser
from django.test import TestCase, TransactionTestCase

from config.graphql.testing import GraphQLTestCase
from opencontractserver.agents.models import AgentConfiguration
from opencontractserver.annotations.models import Annotation
from opencontractserver.constants.tools import (
    MULTI_CORPUS_SEARCH_MAX_TOP_K,
    MULTI_CORPUS_SEARCH_SNIPPET_MAX_CHARS,
)
from opencontractserver.corpuses.models import Corpus, CorpusGroup
from opencontractserver.corpuses.services import CorpusGroupService
from opencontractserver.corpuses.services.corpus_groups import GROUP_NOT_FOUND_MESSAGE
from opencontractserver.documents.models import Document
from opencontractserver.types.enums import PermissionTypes
from opencontractserver.users.models import User
from opencontractserver.utils.ids import to_global_id
from opencontractserver.utils.permissioning import set_permissions_for_obj_to_user


class CorpusGroupModelTests(TestCase):
    """Model-level behaviour: slug auto-generation."""

    def setUp(self):
        self.user = User.objects.create_user(
            username="cg_model_user", password="x", email="cgm@test.com"
        )

    def test_slug_autogenerated_from_title(self):
        group = CorpusGroup.objects.create(title="Bolivian Laws", creator=self.user)
        self.assertEqual(group.slug, "Bolivian-Laws")

    def test_slug_collision_gets_suffix(self):
        first = CorpusGroup.objects.create(title="Same Title", creator=self.user)
        second = CorpusGroup.objects.create(title="Same Title", creator=self.user)
        self.assertNotEqual(first.slug, second.slug)
        self.assertTrue(second.slug.startswith("Same-Title"))

    def test_explicit_slug_preserved(self):
        group = CorpusGroup.objects.create(
            title="Whatever", slug="my-explicit-slug", creator=self.user
        )
        self.assertEqual(group.slug, "my-explicit-slug")

    def test_str_shows_title(self):
        group = CorpusGroup.objects.create(title="Printable", creator=self.user)
        self.assertEqual(str(group), "CorpusGroup(Printable)")


class CorpusGroupServiceTests(TestCase):
    """Service-layer visibility, lookup, and CRUD authorisation."""

    def setUp(self):
        self.owner = User.objects.create_user(
            username="cg_owner", password="x", email="cgo@test.com"
        )
        self.other_owner = User.objects.create_user(
            username="cg_other_owner", password="x", email="cgoo@test.com"
        )
        self.viewer = User.objects.create_user(
            username="cg_viewer", password="x", email="cgv@test.com"
        )
        self.stranger = User.objects.create_user(
            username="cg_stranger", password="x", email="cgstr@test.com"
        )

        # Member corpora with distinct visibility profiles.
        self.owner_corpus = Corpus.objects.create(
            title="Owner Corpus", creator=self.owner, is_public=False
        )
        self.foreign_corpus = Corpus.objects.create(
            title="Foreign Corpus", creator=self.other_owner, is_public=False
        )
        self.public_corpus = Corpus.objects.create(
            title="Public Corpus", creator=self.other_owner, is_public=True
        )
        # ``viewer`` can read the group and the foreign corpus, nothing else.
        set_permissions_for_obj_to_user(
            self.viewer, self.foreign_corpus, [PermissionTypes.READ]
        )

        self.group = CorpusGroup.objects.create(
            title="Mixed Group", creator=self.owner, is_public=False
        )
        # Membership is set directly at the ORM level to simulate drift:
        # a corpus can be in a group even when a given caller can't see it.
        self.group.corpora.set(
            [self.owner_corpus, self.foreign_corpus, self.public_corpus]
        )
        set_permissions_for_obj_to_user(self.viewer, self.group, [PermissionTypes.READ])

    # ---------------------- visibility / lookup ---------------------- #

    def test_list_visible_groups(self):
        self.assertIn(self.group, CorpusGroupService.list_visible_groups(self.owner))
        self.assertIn(self.group, CorpusGroupService.list_visible_groups(self.viewer))
        self.assertNotIn(
            self.group, CorpusGroupService.list_visible_groups(self.stranger)
        )

    def test_public_group_visible_to_stranger_and_anonymous(self):
        public_group = CorpusGroup.objects.create(
            title="Public Group", creator=self.owner, is_public=True
        )
        self.assertIn(
            public_group, CorpusGroupService.list_visible_groups(self.stranger)
        )
        self.assertIn(
            public_group, CorpusGroupService.list_visible_groups(AnonymousUser())
        )

    def test_get_group_by_ref_pk_and_slug(self):
        self.assertEqual(
            CorpusGroupService.get_group_by_ref(self.owner, self.group.pk), self.group
        )
        self.assertEqual(
            CorpusGroupService.get_group_by_ref(self.owner, str(self.group.pk)),
            self.group,
        )
        self.assertEqual(
            CorpusGroupService.get_group_by_ref(self.owner, self.group.slug),
            self.group,
        )

    def test_get_group_by_ref_idor_uniform_none(self):
        """Invisible and nonexistent groups are indistinguishable (both None)."""
        self.assertIsNone(
            CorpusGroupService.get_group_by_ref(self.stranger, self.group.pk)
        )
        self.assertIsNone(
            CorpusGroupService.get_group_by_ref(self.stranger, self.group.slug)
        )
        self.assertIsNone(
            CorpusGroupService.get_group_by_ref(self.owner, "no-such-slug")
        )
        self.assertIsNone(CorpusGroupService.get_group_by_ref(self.owner, ""))

    def test_group_corpora_filtered_per_user(self):
        """MIN(corpus_permission, group_membership): each caller sees only
        the member corpora they can READ."""
        owner_sees = set(
            CorpusGroupService.get_group_corpora_visible_to_user(self.owner, self.group)
        )
        self.assertEqual(owner_sees, {self.owner_corpus, self.public_corpus})

        viewer_sees = set(
            CorpusGroupService.get_group_corpora_visible_to_user(
                self.viewer, self.group
            )
        )
        self.assertEqual(viewer_sees, {self.foreign_corpus, self.public_corpus})

        anon_sees = set(
            CorpusGroupService.get_group_corpora_visible_to_user(
                AnonymousUser(), self.group
            )
        )
        self.assertEqual(anon_sees, {self.public_corpus})

    def test_group_corpora_resolved_at_call_time(self):
        """Membership changes apply on the very next call — no snapshot."""
        new_corpus = Corpus.objects.create(
            title="Late Addition", creator=self.owner, is_public=False
        )
        before = set(
            CorpusGroupService.get_group_corpora_visible_to_user(self.owner, self.group)
        )
        self.assertNotIn(new_corpus, before)

        self.group.corpora.add(new_corpus)
        after = set(
            CorpusGroupService.get_group_corpora_visible_to_user(self.owner, self.group)
        )
        self.assertIn(new_corpus, after)

    # ------------------------------ CRUD ------------------------------ #

    def test_create_group_requires_authentication(self):
        result = CorpusGroupService.create_group(AnonymousUser(), title="Nope")
        self.assertFalse(result.ok)

    def test_create_group_requires_title(self):
        result = CorpusGroupService.create_group(self.owner, title="   ")
        self.assertFalse(result.ok)
        self.assertIn("Title is required", result.error)

    def test_create_group_with_visible_default_agent(self):
        agent = AgentConfiguration.objects.create(
            name="Visible Orchestrator",
            scope="GLOBAL",
            is_active=True,
            is_public=True,
            creator=self.owner,
            system_instructions="orchestrate",
        )
        result = CorpusGroupService.create_group(
            self.owner, title="With Agent", default_agent_pk=agent.pk
        )
        self.assertTrue(result.ok)
        created = result.value
        assert created is not None  # narrow for mypy
        self.assertEqual(created.default_agent, agent)

    def test_create_group_rejects_invisible_corpora(self):
        """A corpus the caller cannot READ fails creation with a message
        that does not distinguish missing from forbidden."""
        result = CorpusGroupService.create_group(
            self.stranger,
            title="Probe",
            corpus_pks=[self.owner_corpus.pk],
        )
        self.assertFalse(result.ok)
        self.assertIn("Corpora not found", result.error)

        missing_result = CorpusGroupService.create_group(
            self.stranger,
            title="Probe2",
            corpus_pks=[999999],
        )
        self.assertFalse(missing_result.ok)
        self.assertIn("Corpora not found", missing_result.error)

    def test_explicit_slug_collision_fails_cleanly(self):
        """An explicit slug that collides with an existing group surfaces a
        friendly failure from create AND update — never a raw DB
        IntegrityError (auto-generated slugs de-duplicate in ``save()``)."""
        CorpusGroup.objects.create(
            title="Slug Holder", slug="taken-slug", creator=self.owner
        )
        create_result = CorpusGroupService.create_group(
            self.owner, title="Another", slug="taken-slug"
        )
        self.assertFalse(create_result.ok)
        self.assertIn("already exists", create_result.error)

        update_result = CorpusGroupService.update_group(
            self.owner, self.group, slug="taken-slug"
        )
        self.assertFalse(update_result.ok)
        self.assertIn("already exists", update_result.error)

    def test_create_group_rejects_non_numeric_corpus_pks(self):
        """A non-numeric pk (e.g. a well-formed global id that decoded to a
        garbage string) surfaces the uniform "Corpora not found" failure —
        never a raw int-coercion ValueError out of the queryset."""
        result = CorpusGroupService.create_group(
            self.owner,
            title="Probe3",
            corpus_pks=["abc", self.owner_corpus.pk],
        )
        self.assertFalse(result.ok)
        self.assertIn("Corpora not found: abc", result.error)

    def test_create_group_grants_creator_crud(self):
        result = CorpusGroupService.create_group(
            self.owner,
            title="My Group",
            corpus_pks=[self.owner_corpus.pk, self.public_corpus.pk],
        )
        self.assertTrue(result.ok)
        group = result.value
        assert group is not None  # narrow for mypy
        self.assertEqual(
            set(group.corpora.all()), {self.owner_corpus, self.public_corpus}
        )
        update = CorpusGroupService.update_group(
            self.owner, group, title="Renamed Group"
        )
        self.assertTrue(update.ok)
        updated = update.value
        assert updated is not None  # narrow for mypy
        self.assertEqual(updated.title, "Renamed Group")

    def test_create_group_with_invisible_default_agent_fails(self):
        private_agent = AgentConfiguration.objects.create(
            name="Private Agent",
            scope="GLOBAL",
            is_active=False,  # inactive global agents are invisible to others
            is_public=False,
            creator=self.other_owner,
            system_instructions="hidden",
        )
        result = CorpusGroupService.create_group(
            self.owner,
            title="Agent Probe",
            default_agent_pk=private_agent.pk,
        )
        self.assertFalse(result.ok)
        self.assertIn("Agent configuration not found", result.error)

    def test_update_group_denied_for_non_owner(self):
        result = CorpusGroupService.update_group(
            self.stranger, self.group, title="Hijack"
        )
        self.assertFalse(result.ok)
        self.assertEqual(result.error, GROUP_NOT_FOUND_MESSAGE)

    def test_update_group_rejects_invisible_corpus(self):
        """Membership replacement is gated by per-corpus READ, same as create."""
        stranger_corpus = Corpus.objects.create(
            title="Stranger Corpus", creator=self.stranger, is_public=False
        )
        result = CorpusGroupService.update_group(
            self.owner, self.group, corpus_pks=[stranger_corpus.pk]
        )
        self.assertFalse(result.ok)
        self.assertIn("Corpora not found", result.error)

    def test_update_group_rejects_invisible_default_agent(self):
        invisible_agent = AgentConfiguration.objects.create(
            name="Invisible Agent",
            scope="GLOBAL",
            is_active=False,
            is_public=False,
            creator=self.other_owner,
            system_instructions="hidden",
        )
        result = CorpusGroupService.update_group(
            self.owner, self.group, default_agent_pk=invisible_agent.pk
        )
        self.assertFalse(result.ok)
        self.assertIn("Agent configuration not found", result.error)

    def test_update_group_replaces_visible_membership_and_clears_agent(self):
        agent = AgentConfiguration.objects.create(
            name="Orchestrator",
            scope="GLOBAL",
            is_active=True,
            is_public=True,
            creator=self.owner,
            system_instructions="orchestrate",
        )
        set_result = CorpusGroupService.update_group(
            self.owner,
            self.group,
            corpus_pks=[self.owner_corpus.pk],
            default_agent_pk=agent.pk,
        )
        self.assertTrue(set_result.ok)
        # ``public_corpus`` was a VISIBLE member and was correctly dropped —
        # removal still works. ``foreign_corpus`` is invisible to ``owner``, so
        # it is preserved rather than silently destroyed (see
        # ``test_update_group_preserves_invisible_member_on_unrelated_edit``).
        self.assertEqual(
            set(self.group.corpora.all()), {self.owner_corpus, self.foreign_corpus}
        )
        set_group = set_result.value
        assert set_group is not None  # narrow for mypy
        self.assertEqual(set_group.default_agent, agent)

        clear_result = CorpusGroupService.update_group(
            self.owner, self.group, clear_default_agent=True
        )
        self.assertTrue(clear_result.ok)
        cleared_group = clear_result.value
        assert cleared_group is not None  # narrow for mypy
        self.assertIsNone(cleared_group.default_agent)

    def test_update_group_preserves_invisible_member_on_unrelated_edit(self):
        """A member the caller cannot READ survives a title-only edit.

        Regression: the edit form is seeded from the per-viewer-filtered
        ``CorpusGroupType.corpora``, so it can only ever resubmit the members
        the caller can currently READ. A wholesale ``corpora.set(submitted)``
        therefore silently destroyed any member that had since become
        invisible to the caller — unrecoverable data loss the caller could
        neither see nor detect. Membership replacement now replaces only the
        caller-visible slice.
        """
        # ``foreign_corpus`` is a real member but invisible to ``owner``
        # (created by ``other_owner``, private, no grant) — exactly the
        # "was public when added, made private later" drift scenario.
        self.assertNotIn(
            self.foreign_corpus,
            CorpusGroupService.get_group_corpora_visible_to_user(
                self.owner, self.group
            ),
        )
        self.assertIn(self.foreign_corpus, self.group.corpora.all())

        # The owner edits ONLY the title. The form resubmits precisely what it
        # could see — omitting ``corpus_pks`` would skip the M2M write entirely
        # and would not exercise the bug at all.
        result = CorpusGroupService.update_group(
            self.owner,
            self.group,
            title="Renamed Only",
            corpus_pks=[self.owner_corpus.pk, self.public_corpus.pk],
        )
        self.assertTrue(result.ok, result.error)

        self.assertEqual(
            set(self.group.corpora.all()),
            {self.owner_corpus, self.public_corpus, self.foreign_corpus},
            "invisible member was destroyed by an edit that never showed it",
        )
        self.group.refresh_from_db()
        self.assertEqual(self.group.title, "Renamed Only")

    def test_update_group_can_still_remove_a_visible_member(self):
        """Preserving invisible members must not make membership append-only."""
        self.assertIn(self.public_corpus, self.group.corpora.all())
        self.assertIn(
            self.public_corpus,
            CorpusGroupService.get_group_corpora_visible_to_user(
                self.owner, self.group
            ),
        )

        # Drop the visible ``public_corpus`` by omitting it from the submission.
        result = CorpusGroupService.update_group(
            self.owner, self.group, corpus_pks=[self.owner_corpus.pk]
        )
        self.assertTrue(result.ok, result.error)
        self.assertNotIn(self.public_corpus, self.group.corpora.all())
        # ...while the invisible member is still preserved.
        self.assertIn(self.foreign_corpus, self.group.corpora.all())

        # Removing every visible member is likewise allowed.
        cleared = CorpusGroupService.update_group(self.owner, self.group, corpus_pks=[])
        self.assertTrue(cleared.ok, cleared.error)
        self.assertEqual(set(self.group.corpora.all()), {self.foreign_corpus})

    def test_delete_group_denied_then_allowed(self):
        denied = CorpusGroupService.delete_group(self.stranger, self.group)
        self.assertFalse(denied.ok)
        self.assertEqual(denied.error, GROUP_NOT_FOUND_MESSAGE)

        allowed = CorpusGroupService.delete_group(self.owner, self.group)
        self.assertTrue(allowed.ok)
        self.assertFalse(CorpusGroup.objects.filter(pk=self.group.pk).exists())
        # Member corpora are untouched by group deletion.
        self.assertTrue(Corpus.objects.filter(pk=self.owner_corpus.pk).exists())


class _FakeVectorStore:
    """Stand-in for ``CoreAnnotationVectorStore`` that records construction
    and returns canned per-corpus results without touching embedders."""

    instances: list[_FakeVectorStore] = []
    results_by_corpus: dict[int, list] = {}
    raise_for_corpus_ids: set[int] = set()

    def __init__(self, user_id=None, corpus_id=None, embedder_path=None, **kwargs):
        self.user_id = user_id
        self.corpus_id = corpus_id
        self.embedder_path = embedder_path
        self.queries: list = []
        type(self).instances.append(self)

    async def async_search(self, query):
        self.queries.append(query)
        if self.corpus_id in type(self).raise_for_corpus_ids:
            raise RuntimeError("boom")
        return type(self).results_by_corpus.get(self.corpus_id, [])

    @classmethod
    def reset(cls):
        cls.instances = []
        cls.results_by_corpus = {}
        cls.raise_for_corpus_ids = set()


class SearchAcrossCorporaToolTests(TransactionTestCase):
    """Behavioural tests for the ``search_across_corpora`` agent tool.

    ``TransactionTestCase`` because the tool issues ORM calls through
    ``sync_to_async`` worker threads whose connections cannot see an outer
    ``TestCase`` transaction.
    """

    serialized_rollback = False

    def setUp(self):
        from opencontractserver.llms.vector_stores.core_vector_stores import (
            VectorSearchResult,
        )

        _FakeVectorStore.reset()
        self.VectorSearchResult = VectorSearchResult

        self.user = User.objects.create_user(
            username="tool_user", password="x", email="tool@test.com"
        )
        self.other = User.objects.create_user(
            username="tool_other", password="x", email="toolo@test.com"
        )

        self.visible_corpus = Corpus.objects.create(
            title="Visible Corpus", creator=self.user, is_public=False
        )
        self.hidden_corpus = Corpus.objects.create(
            title="Hidden Corpus", creator=self.other, is_public=False
        )

        self.doc = Document.objects.create(title="Doc A", creator=self.user)
        self.doc, _, _ = self.visible_corpus.add_document(
            document=self.doc, user=self.user
        )
        self.annotation = Annotation.objects.create(
            document=self.doc,
            corpus=self.visible_corpus,
            creator=self.user,
            raw_text="A relevant passage about water rights.",
            page=3,
        )

        self.group = CorpusGroup.objects.create(
            title="Tool Group", creator=self.user, is_public=False
        )
        self.group.corpora.set([self.visible_corpus, self.hidden_corpus])

    def _run_tool(self, **kwargs):
        from opencontractserver.llms.tools.core_tools import asearch_across_corpora

        with patch(
            "opencontractserver.llms.vector_stores.core_vector_stores"
            ".CoreAnnotationVectorStore",
            _FakeVectorStore,
        ):
            return async_to_sync(asearch_across_corpora)(**kwargs)

    def test_invisible_group_raises_uniform_error(self):
        """Missing and forbidden groups raise the identical message shape."""
        for ref in (self.group.slug, "no-such-group"):
            with self.assertRaises(ValueError) as ctx:
                self._run_tool(
                    query="anything", corpus_group=ref, user_id=self.other.id
                )
            self.assertIn("does not exist or is not accessible", str(ctx.exception))

    def test_searches_only_visible_corpora_and_tags_results(self):
        _FakeVectorStore.results_by_corpus = {
            self.visible_corpus.id: [
                self.VectorSearchResult(
                    annotation=self.annotation, similarity_score=0.87
                )
            ]
        }
        payload = self._run_tool(
            query="water rights",
            corpus_group=self.group.slug,
            user_id=self.user.id,
        )

        # Only the visible member corpus was searched.
        searched_ids = {store.corpus_id for store in _FakeVectorStore.instances}
        self.assertEqual(searched_ids, {self.visible_corpus.id})

        self.assertEqual(payload["corpus_group_id"], self.group.pk)
        self.assertEqual(payload["corpus_group_slug"], self.group.slug)
        self.assertEqual(payload["searched_corpora"], 1)
        self.assertEqual(payload["corpora_truncated"], 0)

        [corpus_entry] = payload["results_by_corpus"]
        self.assertEqual(corpus_entry["corpus_id"], self.visible_corpus.id)
        self.assertEqual(corpus_entry["corpus_title"], "Visible Corpus")
        [hit] = corpus_entry["results"]
        self.assertEqual(hit["annotation_id"], self.annotation.id)
        self.assertEqual(hit["document_id"], self.doc.id)
        self.assertEqual(hit["document_title"], "Doc A")
        self.assertEqual(hit["page"], 3)
        self.assertEqual(hit["similarity_score"], 0.87)
        self.assertIn("water rights", hit["content"])

    def test_group_membership_resolved_at_call_time(self):
        """A corpus added to the group AFTER agent configuration is searched
        on the very next call — the tool never snapshots membership."""
        self._run_tool(query="q", corpus_group=self.group.slug, user_id=self.user.id)
        first_pass = {store.corpus_id for store in _FakeVectorStore.instances}
        self.assertEqual(first_pass, {self.visible_corpus.id})

        late_corpus = Corpus.objects.create(
            title="Late Corpus", creator=self.user, is_public=False
        )
        self.group.corpora.add(late_corpus)

        _FakeVectorStore.instances = []
        self._run_tool(query="q", corpus_group=self.group.slug, user_id=self.user.id)
        second_pass = {store.corpus_id for store in _FakeVectorStore.instances}
        self.assertEqual(second_pass, {self.visible_corpus.id, late_corpus.id})

    def test_group_document_resolver_requires_visible_current_member(self):
        """Cross-corpus document follow-up uses the live group visibility gate."""
        from opencontractserver.llms.tools.core_tools.multi_corpus import (
            _resolve_group_document,
        )

        document, corpus = _resolve_group_document(
            self.group.slug, self.doc.id, self.user.id
        )
        self.assertEqual(document.id, self.doc.id)
        self.assertEqual(corpus.id, self.visible_corpus.id)

        hidden_doc = Document.objects.create(
            title="Hidden Group Document", creator=self.other
        )
        hidden_doc, _, _ = self.hidden_corpus.add_document(
            document=hidden_doc, user=self.other
        )
        with self.assertRaises(ValueError) as ctx:
            _resolve_group_document(self.group.slug, hidden_doc.id, self.user.id)
        self.assertEqual(
            str(ctx.exception),
            "Document is not available in the selected corpus group.",
        )

    def test_k_clamped_to_max(self):
        self._run_tool(
            query="q",
            corpus_group=self.group.slug,
            k=99999,
            user_id=self.user.id,
        )
        [store] = _FakeVectorStore.instances
        [query] = store.queries
        self.assertEqual(query.similarity_top_k, MULTI_CORPUS_SEARCH_MAX_TOP_K)

    def test_per_corpus_failure_is_isolated(self):
        late_corpus = Corpus.objects.create(
            title="Failing Corpus", creator=self.user, is_public=False
        )
        self.group.corpora.add(late_corpus)
        _FakeVectorStore.raise_for_corpus_ids = {late_corpus.id}
        _FakeVectorStore.results_by_corpus = {
            self.visible_corpus.id: [
                self.VectorSearchResult(
                    annotation=self.annotation, similarity_score=0.5
                )
            ]
        }

        payload = self._run_tool(
            query="q", corpus_group=self.group.slug, user_id=self.user.id
        )
        by_corpus = {e["corpus_id"]: e for e in payload["results_by_corpus"]}
        self.assertIn("error", by_corpus[late_corpus.id])
        self.assertEqual(by_corpus[late_corpus.id]["results"], [])
        self.assertEqual(len(by_corpus[self.visible_corpus.id]["results"]), 1)

    def test_corpora_beyond_cap_are_truncated_and_reported(self):
        """Visible members beyond the per-call cap are dropped from the
        search but surfaced in ``corpora_truncated`` — never silently."""
        extra_corpus = Corpus.objects.create(
            title="Extra Corpus", creator=self.user, is_public=False
        )
        self.group.corpora.add(extra_corpus)
        with patch(
            "opencontractserver.llms.tools.core_tools.multi_corpus"
            ".MULTI_CORPUS_SEARCH_MAX_CORPORA",
            1,
        ):
            payload = self._run_tool(
                query="q", corpus_group=self.group.slug, user_id=self.user.id
            )
        self.assertEqual(payload["searched_corpora"], 1)
        self.assertEqual(payload["corpora_truncated"], 1)
        self.assertEqual(len(payload["results_by_corpus"]), 1)

    def test_content_snippet_is_bounded(self):
        self.annotation.raw_text = "x" * (MULTI_CORPUS_SEARCH_SNIPPET_MAX_CHARS * 3)
        self.annotation.save()
        _FakeVectorStore.results_by_corpus = {
            self.visible_corpus.id: [
                self.VectorSearchResult(
                    annotation=self.annotation, similarity_score=0.5
                )
            ]
        }
        payload = self._run_tool(
            query="q", corpus_group=self.group.slug, user_id=self.user.id
        )
        [corpus_entry] = payload["results_by_corpus"]
        [hit] = corpus_entry["results"]
        self.assertLessEqual(len(hit["content"]), MULTI_CORPUS_SEARCH_SNIPPET_MAX_CHARS)

    def test_tool_is_registered(self):
        """``search_across_corpora`` resolves from the tool registry (the
        name AgentConfiguration.available_tools entries use)."""
        from opencontractserver.llms.tools.tool_registry import ToolFunctionRegistry

        core_tool = ToolFunctionRegistry.get().to_core_tool("search_across_corpora")
        assert core_tool is not None  # narrow for mypy
        self.assertEqual(core_tool.name, "search_across_corpora")


CORPUS_GROUPS_MINE_QUERY = """
    query CorpusGroups($mine: Boolean) {
        corpusGroups(mine: $mine) {
            edges { node { id title } }
        }
    }
"""


class CorpusGroupMineFilterTests(GraphQLTestCase):
    """The ``mine`` scope filter on the ``corpusGroups`` connection (#2141).

    ``mine`` narrows an already visibility-scoped queryset
    (``CorpusGroupService.list_visible_groups`` runs before the filterset), so
    every assertion here pins *narrowing*, never widening. Per the
    ``OwnershipScopeFilterMixin`` contract the flag is opt-in only: ``False``
    and omission are both no-ops, never an inversion.
    """

    GRAPHQL_URL = "/graphql/"
    me: User
    other: User
    my_group: CorpusGroup
    other_public_group: CorpusGroup

    @classmethod
    def setUpTestData(cls):
        cls.me = User.objects.create_user(
            username="cg_mine_me", password="testpass", email="cgmine@test.com"
        )
        cls.other = User.objects.create_user(
            username="cg_mine_other", password="testpass", email="cgmineo@test.com"
        )
        cls.my_group = CorpusGroup.objects.create(
            title="Mine Filter Own Group", creator=cls.me, is_public=False
        )
        # A group owned by somebody ELSE that ``me`` can nonetheless see.
        cls.other_public_group = CorpusGroup.objects.create(
            title="Mine Filter Foreign Public Group",
            creator=cls.other,
            is_public=True,
        )

    def _titles(self, variables: dict | None = None) -> set[str]:
        response = self.query(CORPUS_GROUPS_MINE_QUERY, variables=variables)
        self.assertResponseNoErrors(response)
        return {
            edge["node"]["title"]
            for edge in response.json()["data"]["corpusGroups"]["edges"]
        }

    def test_mine_returns_only_own_groups(self):
        self.client.login(username="cg_mine_me", password="testpass")
        self.assertEqual(self._titles({"mine": True}), {self.my_group.title})

    def test_foreign_public_group_visible_but_excluded_by_mine(self):
        """The acceptance criterion: groups the caller does not own are not
        listed under ``mine: true``.

        Both halves are asserted — the foreign public group IS returned by the
        unfiltered query and is NOT returned under ``mine: true`` — so the
        test cannot pass by way of the group being invisible for some
        unrelated reason. Only ``mine`` can explain the difference.
        """
        self.client.login(username="cg_mine_me", password="testpass")
        self.assertIn(self.other_public_group.title, self._titles())
        self.assertNotIn(self.other_public_group.title, self._titles({"mine": True}))

    def test_mine_false_and_omitted_are_no_ops(self):
        """``mine`` is opt-in: ``False`` behaves exactly like omitting it and
        returns the full visible set (it does NOT invert to "not mine")."""
        self.client.login(username="cg_mine_me", password="testpass")
        expected = {self.my_group.title, self.other_public_group.title}
        self.assertEqual(self._titles(), expected)
        self.assertEqual(self._titles({"mine": False}), expected)

    def test_anonymous_mine_returns_empty_connection_not_error(self):
        """An anonymous caller has no owned groups — the connection is empty
        rather than a GraphQL error (``assertResponseNoErrors`` in
        ``_titles``). The unfiltered query still returns the public group, so
        the empty result is attributable to ``mine``, not to anonymity."""
        self.assertEqual(self._titles(), {self.other_public_group.title})
        self.assertEqual(self._titles({"mine": True}), set())


class CorpusGroupGraphQLTests(GraphQLTestCase):
    """Permission boundaries on the GraphQL surface."""

    GRAPHQL_URL = "/graphql/"
    owner: User
    stranger: User
    owner_corpus: Corpus
    public_corpus: Corpus
    group: CorpusGroup

    @classmethod
    def setUpTestData(cls):
        cls.owner = User.objects.create_user(
            username="gql_cg_owner", password="testpass", email="gqlo@test.com"
        )
        cls.stranger = User.objects.create_user(
            username="gql_cg_stranger", password="testpass", email="gqls@test.com"
        )
        cls.owner_corpus = Corpus.objects.create(
            title="GQL Owner Corpus", creator=cls.owner, is_public=False
        )
        cls.public_corpus = Corpus.objects.create(
            title="GQL Public Corpus", creator=cls.owner, is_public=True
        )
        cls.group = CorpusGroup.objects.create(
            title="GQL Group", creator=cls.owner, is_public=True
        )
        cls.group.corpora.set([cls.owner_corpus, cls.public_corpus])

    def test_corpus_groups_query_visibility(self):
        private_group = CorpusGroup.objects.create(
            title="GQL Private Group", creator=self.owner, is_public=False
        )
        self.client.login(username="gql_cg_stranger", password="testpass")
        response = self.query("""
            query {
                corpusGroups {
                    edges { node { id title } }
                }
            }
            """)
        self.assertResponseNoErrors(response)
        titles = {
            e["node"]["title"] for e in response.json()["data"]["corpusGroups"]["edges"]
        }
        self.assertIn("GQL Group", titles)
        self.assertNotIn(private_group.title, titles)

    def test_member_corpora_filtered_per_viewer(self):
        """The public group is visible to the stranger, but its private
        member corpus is not listed for them."""
        self.client.login(username="gql_cg_stranger", password="testpass")
        response = self.query("""
            query {
                corpusGroups {
                    edges {
                        node {
                            title
                            corpora { edges { node { title } } }
                        }
                    }
                }
            }
            """)
        self.assertResponseNoErrors(response)
        edges = response.json()["data"]["corpusGroups"]["edges"]
        node = next(e["node"] for e in edges if e["node"]["title"] == "GQL Group")
        member_titles = {e["node"]["title"] for e in node["corpora"]["edges"]}
        self.assertEqual(member_titles, {"GQL Public Corpus"})

    def test_default_agent_gated_per_viewer(self):
        """``defaultAgent`` is null for viewers who cannot see the bound
        agent (here: a corpus-scoped agent on a private corpus), while a
        viewer with corpus access still resolves it — the binding must not
        leak a private agent's config through a public group."""
        private_agent = AgentConfiguration.objects.create(
            name="Private Orchestrator",
            scope="CORPUS",
            corpus=self.owner_corpus,  # private corpus -> agent invisible to stranger
            is_active=True,
            is_public=False,
            creator=self.owner,
            system_instructions="sensitive persona",
        )
        agent_group = CorpusGroup.objects.create(
            title="GQL Agent Group",
            creator=self.owner,
            is_public=True,
            default_agent=private_agent,
        )
        query = """
            query {
                corpusGroups {
                    edges { node { title defaultAgent { id name } } }
                }
            }
            """

        self.client.login(username="gql_cg_stranger", password="testpass")
        response = self.query(query)
        self.assertResponseNoErrors(response)
        edges = response.json()["data"]["corpusGroups"]["edges"]
        node = next(e["node"] for e in edges if e["node"]["title"] == agent_group.title)
        self.assertIsNone(node["defaultAgent"])

        self.client.logout()
        self.client.login(username="gql_cg_owner", password="testpass")
        response = self.query(query)
        self.assertResponseNoErrors(response)
        edges = response.json()["data"]["corpusGroups"]["edges"]
        node = next(e["node"] for e in edges if e["node"]["title"] == agent_group.title)
        self.assertIsNotNone(node["defaultAgent"])
        self.assertEqual(node["defaultAgent"]["name"], "Private Orchestrator")

    def test_create_corpus_group_non_numeric_decoded_pk(self):
        """A well-formed global id that decodes to a non-numeric pk gets the
        uniform "Corpora not found" envelope — not a raw int-coercion error
        through the outer exception handler."""
        self.client.login(username="gql_cg_owner", password="testpass")
        response = self.query(
            """
            mutation($title: String!, $corpusIds: [ID]) {
                createCorpusGroup(title: $title, corpusIds: $corpusIds) {
                    ok
                    message
                }
            }
            """,
            variables={
                "title": "Garbage Pk Group",
                "corpusIds": [to_global_id("CorpusType", "abc")],
            },
        )
        self.assertResponseNoErrors(response)
        data = response.json()["data"]["createCorpusGroup"]
        self.assertFalse(data["ok"])
        self.assertIn("Corpora not found: abc", data["message"])

    def test_create_corpus_group_mutation(self):
        self.client.login(username="gql_cg_owner", password="testpass")
        response = self.query(
            """
            mutation($title: String!, $corpusIds: [ID]) {
                createCorpusGroup(title: $title, corpusIds: $corpusIds) {
                    ok
                    message
                    corpusGroup { title slug corpora { edges { node { title } } } }
                }
            }
            """,
            variables={
                "title": "Created Via GQL",
                "corpusIds": [to_global_id("CorpusType", self.owner_corpus.pk)],
            },
        )
        self.assertResponseNoErrors(response)
        data = response.json()["data"]["createCorpusGroup"]
        self.assertTrue(data["ok"], data["message"])
        self.assertEqual(data["corpusGroup"]["title"], "Created Via GQL")
        self.assertTrue(data["corpusGroup"]["slug"])

    def test_create_corpus_group_rejects_invisible_corpus(self):
        private_corpus = Corpus.objects.create(
            title="Someone Elses Corpus", creator=self.owner, is_public=False
        )
        self.client.login(username="gql_cg_stranger", password="testpass")
        response = self.query(
            """
            mutation($title: String!, $corpusIds: [ID]) {
                createCorpusGroup(title: $title, corpusIds: $corpusIds) {
                    ok
                    message
                }
            }
            """,
            variables={
                "title": "Probe Group",
                "corpusIds": [to_global_id("CorpusType", private_corpus.pk)],
            },
        )
        self.assertResponseNoErrors(response)
        data = response.json()["data"]["createCorpusGroup"]
        self.assertFalse(data["ok"])
        self.assertIn("Corpora not found", data["message"])

    def test_update_corpus_group_denied_for_stranger(self):
        self.client.login(username="gql_cg_stranger", password="testpass")
        response = self.query(
            """
            mutation($id: ID!, $title: String) {
                updateCorpusGroup(corpusGroupId: $id, title: $title) {
                    ok
                    message
                }
            }
            """,
            variables={
                "id": to_global_id("CorpusGroupType", self.group.pk),
                "title": "Hijacked",
            },
        )
        self.assertResponseNoErrors(response)
        data = response.json()["data"]["updateCorpusGroup"]
        self.assertFalse(data["ok"])
        self.assertEqual(data["message"], GROUP_NOT_FOUND_MESSAGE)

    def test_delete_corpus_group_by_owner(self):
        doomed = CorpusGroup.objects.create(
            title="Doomed Group", creator=self.owner, is_public=False
        )
        self.client.login(username="gql_cg_owner", password="testpass")
        response = self.query(
            """
            mutation($id: ID!) {
                deleteCorpusGroup(corpusGroupId: $id) {
                    ok
                    message
                }
            }
            """,
            variables={"id": to_global_id("CorpusGroupType", doomed.pk)},
        )
        self.assertResponseNoErrors(response)
        data = response.json()["data"]["deleteCorpusGroup"]
        self.assertTrue(data["ok"], data["message"])
        self.assertFalse(CorpusGroup.objects.filter(pk=doomed.pk).exists())

    def test_create_corpus_group_malformed_corpus_id(self):
        self.client.login(username="gql_cg_owner", password="testpass")
        response = self.query(
            """
            mutation($title: String!, $corpusIds: [ID]) {
                createCorpusGroup(title: $title, corpusIds: $corpusIds) {
                    ok
                    message
                }
            }
            """,
            variables={"title": "Bad Ids", "corpusIds": ["!!not-a-global-id!!"]},
        )
        self.assertResponseNoErrors(response)
        data = response.json()["data"]["createCorpusGroup"]
        self.assertFalse(data["ok"])
        self.assertEqual(data["message"], "Malformed id argument")

    def test_update_corpus_group_by_owner_succeeds(self):
        target = CorpusGroup.objects.create(
            title="Updatable Group", creator=self.owner, is_public=False
        )
        self.client.login(username="gql_cg_owner", password="testpass")
        response = self.query(
            """
            mutation($id: ID!, $title: String, $slug: String,
                     $description: String, $isPublic: Boolean) {
                updateCorpusGroup(
                    corpusGroupId: $id, title: $title, slug: $slug,
                    description: $description, isPublic: $isPublic
                ) {
                    ok
                    message
                    corpusGroup { title slug description isPublic }
                }
            }
            """,
            variables={
                "id": to_global_id("CorpusGroupType", target.pk),
                "title": "Updated Title",
                "slug": "updated-slug",
                "description": "Updated description",
                "isPublic": True,
            },
        )
        self.assertResponseNoErrors(response)
        data = response.json()["data"]["updateCorpusGroup"]
        self.assertTrue(data["ok"], data["message"])
        self.assertEqual(data["corpusGroup"]["title"], "Updated Title")
        self.assertEqual(data["corpusGroup"]["slug"], "updated-slug")
        self.assertEqual(data["corpusGroup"]["description"], "Updated description")
        self.assertTrue(data["corpusGroup"]["isPublic"])

    def test_update_corpus_group_malformed_and_missing_ids(self):
        self.client.login(username="gql_cg_owner", password="testpass")
        for group_id in ("!!not-a-global-id!!", to_global_id("CorpusGroupType", 0)):
            response = self.query(
                """
                mutation($id: ID!, $title: String) {
                    updateCorpusGroup(corpusGroupId: $id, title: $title) {
                        ok
                        message
                    }
                }
                """,
                variables={"id": group_id, "title": "Whatever"},
            )
            self.assertResponseNoErrors(response)
            data = response.json()["data"]["updateCorpusGroup"]
            self.assertFalse(data["ok"])
            self.assertEqual(data["message"], GROUP_NOT_FOUND_MESSAGE)

    def test_update_corpus_group_malformed_argument_ids(self):
        """Malformed ARGUMENT ids (member corpora / default agent) return the
        same "Malformed id argument" envelope as the create mutation; only a
        malformed TARGET id folds into the IDOR-uniform not-found message."""
        self.client.login(username="gql_cg_owner", password="testpass")
        for variables in (
            {"corpusIds": ["!!not-a-global-id!!"]},
            {"defaultAgentId": "!!not-a-global-id!!"},
        ):
            response = self.query(
                """
                mutation($id: ID!, $corpusIds: [ID], $defaultAgentId: ID) {
                    updateCorpusGroup(
                        corpusGroupId: $id,
                        corpusIds: $corpusIds,
                        defaultAgentId: $defaultAgentId
                    ) {
                        ok
                        message
                    }
                }
                """,
                variables={
                    "id": to_global_id("CorpusGroupType", self.group.pk),
                    **variables,
                },
            )
            self.assertResponseNoErrors(response)
            data = response.json()["data"]["updateCorpusGroup"]
            self.assertFalse(data["ok"])
            self.assertEqual(data["message"], "Malformed id argument")

    def test_delete_corpus_group_malformed_and_missing_ids(self):
        self.client.login(username="gql_cg_owner", password="testpass")
        for group_id in ("!!not-a-global-id!!", to_global_id("CorpusGroupType", 0)):
            response = self.query(
                """
                mutation($id: ID!) {
                    deleteCorpusGroup(corpusGroupId: $id) {
                        ok
                        message
                    }
                }
                """,
                variables={"id": group_id},
            )
            self.assertResponseNoErrors(response)
            data = response.json()["data"]["deleteCorpusGroup"]
            self.assertFalse(data["ok"])
            self.assertEqual(data["message"], GROUP_NOT_FOUND_MESSAGE)

    def test_delete_corpus_group_denied_for_read_only_viewer(self):
        """READ (via public visibility) lets a viewer SEE the group but not
        delete it — the CRUD gate returns the uniform not-found message."""
        self.client.login(username="gql_cg_stranger", password="testpass")
        response = self.query(
            """
            mutation($id: ID!) {
                deleteCorpusGroup(corpusGroupId: $id) {
                    ok
                    message
                }
            }
            """,
            variables={"id": to_global_id("CorpusGroupType", self.group.pk)},
        )
        self.assertResponseNoErrors(response)
        data = response.json()["data"]["deleteCorpusGroup"]
        self.assertFalse(data["ok"])
        self.assertEqual(data["message"], GROUP_NOT_FOUND_MESSAGE)
        self.assertTrue(CorpusGroup.objects.filter(pk=self.group.pk).exists())

    def test_mutations_surface_unexpected_service_errors(self):
        """The catch-all handlers log and wrap unexpected exceptions instead
        of leaking a GraphQL error."""
        from config.graphql import corpus_group_mutations as mutations_module

        self.client.login(username="gql_cg_owner", password="testpass")
        gid = to_global_id("CorpusGroupType", self.group.pk)
        cases = [
            (
                "create_group",
                """mutation { createCorpusGroup(title: "Boom") { ok message } }""",
                "createCorpusGroup",
            ),
            (
                "update_group",
                f"""mutation {{ updateCorpusGroup(corpusGroupId: "{gid}",
                    title: "Boom") {{ ok message }} }}""",
                "updateCorpusGroup",
            ),
            (
                "delete_group",
                f"""mutation {{ deleteCorpusGroup(corpusGroupId: "{gid}")
                    {{ ok message }} }}""",
                "deleteCorpusGroup",
            ),
        ]
        for method_name, mutation, payload_key in cases:
            with patch.object(
                mutations_module.CorpusGroupService,
                method_name,
                side_effect=RuntimeError("kaboom"),
            ):
                response = self.query(mutation)
            self.assertResponseNoErrors(response)
            data = response.json()["data"][payload_key]
            self.assertFalse(data["ok"])
            self.assertIn("kaboom", data["message"])
