# Generated by Django 4.2.14 on 2024-08-02 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0003_alter_analysis_user_lock_alter_analyzer_user_lock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyzer",
            name="task_name",
            field=models.CharField(
                blank=True,
                default="opencontractserver.tasks.data_extract_tasks.oc_llama_index_doc_query",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="analyzer",
            name="host_gremlin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="analyzer.gremlinengine",
            ),
        ),
    ]
