# Generated by Django 4.2.14 on 2024-08-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0005_analyzer_one_field_null_constraint_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyzer",
            name="task_name",
            field=models.CharField(
                blank=True, default=None, max_length=1024, null=True
            ),
        ),
    ]
