# Generated by Django 4.2.15 on 2024-08-27 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("corpuses", "0012_corpusaction_disabled_and_more"),
        ("analyzer", "0006_alter_analyzer_task_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="corpus_action",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analyses",
                to="corpuses.corpusaction",
            ),
        ),
    ]
