# Generated by Django 4.2.18 on 2025-02-10 07:07

from django.db import migrations
import opencontractserver.shared.defaults
import opencontractserver.shared.fields


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0009_auto_load_doc_analyzers"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyzer",
            name="input_schema",
            field=opencontractserver.shared.fields.NullableJSONField(
                blank=True,
                default=opencontractserver.shared.defaults.jsonfield_default_value,
                help_text="Optional JSONSchema describing the analyzer input.",
                null=True,
            ),
        ),
    ]
