# Generated by Django 4.2.18 on 2025-02-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0010_analyzer_input_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="error_traceback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="result_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
