apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlm-ingestor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nlm-ingestor
  template:
    metadata:
      labels:
        app: nlm-ingestor
    spec:
      containers:
      - name: nlm-ingestor
        image: jscrudato/nlm-ingestor-opencontracts
        ports:
        - containerPort: 8000
